import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { Mail, Lock, Eye, EyeOff } from 'lucide-react';
import Button from '../components/common/Button';

export default function Login() {
  const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
      const [showPassword, setShowPassword] = useState(false);
        const [error, setError] = useState('');
          const [loading, setLoading] = useState(false);
            const { login } = useAuth();
              const navigate = useNavigate();

                const handleSubmit = async (e) => {
                    e.preventDefault();
                        setError('');
                            setLoading(true);

                                try {
                                      await login(email, password);
                                            navigate('/dashboard');
                                                } catch (err) {
                                                      setError(err.message || 'Failed to login. Please check your credentials.');
                                                          } finally {
                                                                setLoading(false);
                                                                    }
                                                                      };

                                                                        return (
                                                                            <div className="min-h-screen bg-dark-500 flex items-center justify-center p-4">
                                                                                  <div className="w-full max-w-md">
                                                                                          <div className="text-center mb-8">
                                                                                                    <img src="/logo.jpeg" alt="Last Zone Legends" className="w-20 h-20 rounded-2xl mx-auto mb-4 object-cover" />
                                                                                                              <h1 className="text-2xl font-bold text-white">Last Zone Legends</h1>
                                                                                                                        <p className="text-gray-400 mt-1">Admin Panel Login</p>
                                                                                                                                </div>

                                                                                                                                        <div className="bg-dark-300 rounded-2xl p-6 card-shadow">
                                                                                                                                                  {error && (
                                                                                                                                                              <div className="mb-4 p-3 bg-red-500/20 border border-red-500/50 rounded-lg">
                                                                                                                                                                            <p className="text-red-400 text-sm">{error}</p>
                                                                                                                                                                                        </div>
                                                                                                                                                                                                  )}

                                                                                                                                                                                                            <form onSubmit={handleSubmit}>
                                                                                                                                                                                                                        <div className="mb-4">
                                                                                                                                                                                                                                      <label className="block text-sm font-medium text-gray-300 mb-1.5">
                                                                                                                                                                                                                                                      Email Address
                                                                                                                                                                                                                                                                    </label>
                                                                                                                                                                                                                                                                                  <div className="relative">
                                                                                                                                                                                                                                                                                                  <Mail className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-500" />
                                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                                    type="email"
                                                                                                                                                                                                                                                                                                                                                      value={email}
                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                          placeholder="admin@example.com"
                                                                                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full pl-11 pr-4 py-3 rounded-lg bg-dark-200 border border-dark-100 text-white placeholder-gray-500 focus:border-primary-500 focus:ring-1 focus:ring-primary-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="mb-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <label className="block text-sm font-medium text-gray-300 mb-1.5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Password
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="relative">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Lock className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-500" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type={showPassword ? 'text' : 'password'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      placeholder="••••••••"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="w-full pl-11 pr-11 py-3 rounded-lg bg-dark-200 border border-dark-100 text-white placeholder-gray-500 focus:border-primary-500 focus:ring-1 focus:ring-primary-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => setShowPassword(!showPassword)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-300"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {showPassword ? <EyeOff className="w-5 h-5" /> : <Eye className="w-5 h-5" />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    loading={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="w-full py-3"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Sign In
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-center text-gray-500 text-sm mt-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            © 2024 Last Zone Legends. All rights reserved.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                