import React from 'react';
import { BrowserRouter as Router, Routes, Route, Navigate } from 'react-router-dom';
import { AuthProvider, useAuth } from './contexts/AuthContext';
import Layout from './components/layout/Layout';
import Login from './pages/Login';
import Dashboard from './pages/Dashboard';
import Games from './pages/Games';
import Promotions from './pages/Promotions';
import Tournaments from './pages/Tournaments';
import Users from './pages/Users';
import Deposits from './pages/Deposits';
import Transactions from './pages/Transactions';
import Withdrawals from './pages/Withdrawals';
import Lottery from './pages/Lottery';
import Notifications from './pages/Notifications';
import Settings from './pages/Settings';
import SubAdmins from './pages/SubAdmins';
import DemoData from './pages/DemoData';
import Loader from './components/common/Loader';

function PrivateRoute({ children }) {
  const { currentUser, loading } = useAuth();

    if (loading) {
        return (
              <div className="min-h-screen bg-dark-500 flex items-center justify-center">
                      <Loader text="Loading..." />
                            </div>
                                );
                                  }

                                    return currentUser ? children : <Navigate to="/login" />;
                                    }

                                    // Protected route that checks for specific permission
                                    function ProtectedRoute({ children, permission }) {
                                      const { currentUser, loading, hasPermission, isAdmin, getAllowedPages } = useAuth();

                                        if (loading) {
                                            return (
                                                  <div className="min-h-screen bg-dark-500 flex items-center justify-center">
                                                          <Loader text="Loading..." />
                                                                </div>
                                                                    );
                                                                      }

                                                                        if (!currentUser) {
                                                                            return <Navigate to="/login" />;
                                                                              }

                                                                                // Check permission
                                                                                  if (!isAdmin && !hasPermission(permission)) {
                                                                                      // Redirect to first allowed page
                                                                                          const allowedPages = getAllowedPages();
                                                                                              if (allowedPages.length > 0) {
                                                                                                    return <Navigate to={`/${allowedPages[0]}`} />;
                                                                                                        }
                                                                                                            return <Navigate to="/login" />;
                                                                                                              }

                                                                                                                return children;
                                                                                                                }

                                                                                                                // Admin-only route
                                                                                                                function AdminRoute({ children }) {
                                                                                                                  const { currentUser, loading, isAdmin, getAllowedPages } = useAuth();

                                                                                                                    if (loading) {
                                                                                                                        return (
                                                                                                                              <div className="min-h-screen bg-dark-500 flex items-center justify-center">
                                                                                                                                      <Loader text="Loading..." />
                                                                                                                                            </div>
                                                                                                                                                );
                                                                                                                                                  }

                                                                                                                                                    if (!currentUser) {
                                                                                                                                                        return <Navigate to="/login" />;
                                                                                                                                                          }

                                                                                                                                                            if (!isAdmin) {
                                                                                                                                                                // Redirect sub-admin to their first allowed page
                                                                                                                                                                    const allowedPages = getAllowedPages();
                                                                                                                                                                        if (allowedPages.length > 0) {
                                                                                                                                                                              return <Navigate to={`/${allowedPages[0]}`} />;
                                                                                                                                                                                  }
                                                                                                                                                                                      return <Navigate to="/login" />;
                                                                                                                                                                                        }

                                                                                                                                                                                          return children;
                                                                                                                                                                                          }

                                                                                                                                                                                          function PublicRoute({ children }) {
                                                                                                                                                                                            const { currentUser, loading } = useAuth();

                                                                                                                                                                                              if (loading) {
                                                                                                                                                                                                  return (
                                                                                                                                                                                                        <div className="min-h-screen bg-dark-500 flex items-center justify-center">
                                                                                                                                                                                                                <Loader text="Loading..." />
                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                          );
                                                                                                                                                                                                                            }

                                                                                                                                                                                                                              return !currentUser ? children : <Navigate to="/dashboard" />;
                                                                                                                                                                                                                              }

                                                                                                                                                                                                                              function AppRoutes() {
                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                    <Routes>
                                                                                                                                                                                                                                          <Route path="/login" element={
                                                                                                                                                                                                                                                  <PublicRoute>
                                                                                                                                                                                                                                                            <Login />
                                                                                                                                                                                                                                                                    </PublicRoute>
                                                                                                                                                                                                                                                                          } />

                                                                                                                                                                                                                                                                                <Route path="/" element={<Navigate to="/dashboard" />} />

                                                                                                                                                                                                                                                                                      {/* Dashboard - available to all */}
                                                                                                                                                                                                                                                                                            <Route path="/dashboard" element={
                                                                                                                                                                                                                                                                                                    <PrivateRoute>
                                                                                                                                                                                                                                                                                                              <Layout><Dashboard /></Layout>
                                                                                                                                                                                                                                                                                                                      </PrivateRoute>
                                                                                                                                                                                                                                                                                                                            } />

                                                                                                                                                                                                                                                                                                                                  {/* Games - permission required */}
                                                                                                                                                                                                                                                                                                                                        <Route path="/games" element={
                                                                                                                                                                                                                                                                                                                                                <ProtectedRoute permission="games">
                                                                                                                                                                                                                                                                                                                                                          <Layout><Games /></Layout>
                                                                                                                                                                                                                                                                                                                                                                  </ProtectedRoute>
                                                                                                                                                                                                                                                                                                                                                                        } />

                                                                                                                                                                                                                                                                                                                                                                              {/* Promotions - admin only */}
                                                                                                                                                                                                                                                                                                                                                                                    <Route path="/promotions" element={
                                                                                                                                                                                                                                                                                                                                                                                            <AdminRoute>
                                                                                                                                                                                                                                                                                                                                                                                                      <Layout><Promotions /></Layout>
                                                                                                                                                                                                                                                                                                                                                                                                              </AdminRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                    } />

                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Tournaments - permission required */}
                                                                                                                                                                                                                                                                                                                                                                                                                                <Route path="/tournaments" element={
                                                                                                                                                                                                                                                                                                                                                                                                                                        <ProtectedRoute permission="tournaments">
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Layout><Tournaments /></Layout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </ProtectedRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                } />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Users - admin only */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Route path="/users" element={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <AdminRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Layout><Users /></Layout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </AdminRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Deposits - admin only */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Route path="/deposits" element={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <AdminRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Layout><Deposits /></Layout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </AdminRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Transactions - admin only */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Route path="/transactions" element={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <AdminRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Layout><Transactions /></Layout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </AdminRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Withdrawals - admin only */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Route path="/withdrawals" element={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <AdminRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Layout><Withdrawals /></Layout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </AdminRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Lottery - admin only */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Route path="/lottery" element={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <AdminRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Layout><Lottery /></Layout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </AdminRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Notifications - admin only */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Route path="/notifications" element={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <AdminRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Layout><Notifications /></Layout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </AdminRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Sub-Admins - admin only */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Route path="/subadmins" element={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <AdminRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Layout><SubAdmins /></Layout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </AdminRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Settings - admin only */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Route path="/settings" element={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <AdminRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Layout><Settings /></Layout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </AdminRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Demo Data - admin only */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Route path="/demo-data" element={
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <AdminRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Layout><DemoData /></Layout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </AdminRoute>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Route path="*" element={<Navigate to="/dashboard" />} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Routes>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default function App() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Router>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <AuthProvider>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <AppRoutes />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </AuthProvider>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Router>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        